version: '3'

# mariadb 와 redis 는 추후 개발 시 활성화 하여 사용

services:
#  mariadb:
#    container_name: mariadb
#    image: mariadb:10.11  # LTS 버전
#    restart: unless-stopped
#    ports:
#      - '3306:3306'
#    environment:
#      MYSQL_HOST: mariadb
#      MYSQL_ROOT_PASSWORD: root_password
#      #      MYSQL_ROOT_HOST: %
#      MYSQL_DATABASE: laravel
#      MYSQL_USER: laravel
#      MYSQL_PASSWORD: your_password
#      TZ: Asia/Seoul
#    volumes:
#      - ./.database/mariadb:/var/lib/mysql
#      - ./.logs/mariadb:/var/log/mariadb
#    command:
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
#    networks:
#      - app-network
#
#  redis:
#    container_name: redis
#    image: redis:6-alpine
#    restart: unless-stopped
#    privileged: true
#    volumes:
#      - ./.docker/redis/redis.conf:/usr/local/redis/redis.conf
#      - ./.database/redis:/data
#    ports:
#      - '6379:6379'
#    command:
#      - redis-server
#      - /usr/local/redis/redis.conf
#    networks:
#      - app-network

  node:
    container_name: node20
    image: node:20-alpine
    restart: unless-stopped
    volumes:
      - ./src:/var/www
    ports:
      - "3000:3000"
    entrypoint: [ 'npm' ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge